export:
  model:
    chip_arch: XH2a
    hf_model: null
    context_max_length: 2048
    prefill_chunk_length: 256
    use_cache: true
    num_logits_to_keep: 1
    linear_chunk_size: 64
    split_conv_cache: true
    normalize_force_fp32: false
    use_manual_depthwise_conv1d: false
    fuse_gdr_ops: false
    fuse_gdr_block_recurrent_ops: false
    quant_scheme:
      quant_type: w8a8h1_sefp
      nodes:
        lm_head:
          quant_type: w8a8h1_sefp
      ops: {}
    only_first_block: false
    model_type: Qwen3NextForCausalLM
    model_name: qwen3_next_80b_a3b_instruct
    flash_attention:
      enable: false
      q_bits: 8
      s_bits: 8
    visual_config: null
quant:
  algorithm: gptqmodel
  method: autoround
  output_format: gptqmodel_hf
  artifact_format: gptqmodel_hf
  bits: 4
  group_size: 64
  rotation: false
  sym: true
  iters: 200
  format: auto_round:gptqmodel
  calibration:
    dataset: NeelNanda/pile-10k
    nsamples: 128
    seqlen: 2048
  runtime:
    batch_size: 8
    gradient_accumulate_steps: 1
    trust_remote_code: true
    device_map: '0'
    low_gpu_mem_usage: true
  seed: 42
  moe:
    self_attn_bits: 8
    linear_attn_bits: 8
    dense_mlp_bits: 4
    expert_bits: 4
    shared_expert_bits: 8
