quant:
  algorithm: gptqmodel
  method: gptq
  preset: full_multimodal
  rotation: null
  artifact_format: gptqmodel_hf
  output_format: gptqmodel_hf
  bits: 4
  group_size: 64
  sym: true
  iters: 200
  seed: 42
  quant_nontext_module: false
  calibration:
    jsonl: gptqmodel://quantization/calibration/dense_ivsg/gen_data/Qwen3.5-27B.jsonl
    text_key: text
    nsamples: 256
    seqlen: 512
  runtime:
    batch_size: 1
    device_map: auto
    trust_remote_code: true
    offload_to_disk: false
  validation:
    check_quant_text_demo: true
    check_quant_image_demo: true
    check_quant_video_demo: false
    check_quant_audio_demo: false
export:
  model:
    chip_arch: XH2a
    model_type: Gemma4ForConditionalGeneration
    # 该字段仅用作占位，实际会在导出前实时覆盖
    hf_model: null
    # 按照 HuggingFace 上的模型名称填写，全部小写，'.' 和 '-' 改成 '_'
    model_name: gemma_4_31b
    context_max_length: 2048
    prefill_chunk_length: 320
    bidirectional_vision_attention: true
    max_mm_ranges_per_chunk: 1
    flash_attention:
      fuse_sliding_attention: false
      enable: true
      q_bits: 8
      k_bits: 8
      v_bits: 8
      s_bits: 8
      p_bits: 8
    use_cache: true
    num_logits_to_keep: 1
    sliding_kv_cache_input_mode: slice_window
    quant_scheme:
      quant_type: w8a8h1_sefp
      ops: {}
    visual_config:
      export_mode: padded
      image_seq_length: 280
      max_patches: 2520
      patch_size: 16
      pooling_kernel_size: 3
      quant_scheme:
        quant_type: w8a8h1_sefp
        ops: {}
      input_modality: image
    only_first_block: false
    video_visual_config:
      export_mode: padded
      image_seq_length: 70
      max_patches: 630
      patch_size: 16
      pooling_kernel_size: 3
      input_modality: video
      quant_scheme:
        quant_type: w8a8h1_sefp
        ops: {}
    spec_decode_mode: mtp
    num_draft_tokens: 4
    output_post_norm_hidden: true
    mtp_config:
      assistant_hf_model: weights/gemma-4-31B-it-assistant
      target_hf_model: weights/gemma-4-31B-it
      body_quant_type: w8a8h1_sefp
      lm_head_quant_type: w4a8h0_ssfp
      batch_size: 1
      input_sequence_length: 1
      use_cache: true
      num_draft_tokens: 4
      assistant_num_hidden_layers: 4
      assistant_layer_pattern:
      - sliding_attention
      - sliding_attention
      - sliding_attention
      - full_attention
      assistant_hidden_size: 1024
      assistant_num_attention_heads: 32
      assistant_num_key_value_heads: 16
      assistant_num_global_key_value_heads: 4
      head_dim: 256
      use_ordered_embeddings: false
      shared_kv_inputs:
      - shared_key_cache_sliding
      - shared_value_cache_sliding
      - shared_key_cache_full
      - shared_value_cache_full
