import argparse

import xhquant.utils.suppress_printing
import xhquant.xhonnxruntime.config as xhonnxruntime_config

from _runtime import (
    load_runtime_from_meta,
    parse_auto_offload_max_memory,
    parse_dtype,
    postprocess_chat_output,
)


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Qwen3Next hmonnx inference demo",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--config",
        type=str,
        default=(
            "work_dirs/qwen3_next_80b_a3b_instruct/"
            "qwen3_next_80b_a3b_instruct_xh2a_Qwen3-Next-80B-A3B-Instruct/meta.json"
        ),
        help="Path to meta.json generated by qwen3_next_xh2a_export_hmonnx.py",
    )
    parser.add_argument("--prompt", type=str, default="你好呀，你是谁，中文回答", help="Input prompt for single-turn")
    parser.add_argument("--interactive", action="store_true", help="Interactive multi-turn text chat")
    parser.add_argument("--system-prompt", type=str, default="You are a helpful assistant.")
    parser.add_argument("--max-new-tokens", type=int, default=256)
    parser.add_argument("--do-sample", dest="do_sample", action="store_true", default=True)
    parser.add_argument("--no-sample", dest="do_sample", action="store_false")
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top-p", type=float, default=0.8)
    parser.add_argument("--top-k", type=int, default=20)
    parser.add_argument("--repetition-penalty", type=float, default=1.0)
    parser.add_argument("--presence-penalty", type=float, default=1.5)
    parser.add_argument("--stream-output", dest="stream_output", action="store_true", default=True)
    parser.add_argument("--no-stream-output", dest="stream_output", action="store_false")
    parser.add_argument("--dtype", type=str, default="fp16", choices=["fp16", "float16", "half", "fp32", "float32", "bf16", "bfloat16"])
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--exec-device", type=str, default="cuda")
    parser.add_argument("--disable-auto-offload", action="store_true")
    parser.add_argument("--auto-offload-max-memory", type=str, default=None)
    parser.add_argument("--prefill-auto-offload-max-memory", type=str, default=None)
    parser.add_argument("--decode-auto-offload-max-memory", type=str, default=None)
    parser.add_argument("--resource-tight-mode", action="store_true")
    parser.add_argument("--enable-thinking", action="store_true")
    parser.add_argument("--show-runtime-progress", action="store_true")
    return parser


def main():
    args = parse_arguments().parse_args()

    xhquant.utils.suppress_printing.disable_printing = True
    xhonnxruntime_config.disable_progress = not args.show_runtime_progress
    xhonnxruntime_config.verbose_progress = bool(args.show_runtime_progress)

    runtime, tokenizer, _ = load_runtime_from_meta(
        meta_path=args.config,
        dtype=parse_dtype(args.dtype),
        device=args.device,
        exec_device=args.exec_device,
        auto_offload=not args.disable_auto_offload,
        auto_offload_max_memory=parse_auto_offload_max_memory(args.auto_offload_max_memory),
        prefill_auto_offload_max_memory=parse_auto_offload_max_memory(args.prefill_auto_offload_max_memory),
        decode_auto_offload_max_memory=parse_auto_offload_max_memory(args.decode_auto_offload_max_memory),
        resource_tight_mode=args.resource_tight_mode,
    )

    if not args.interactive:
        output = runtime.chat(
            prompt=args.prompt,
            tokenizer=tokenizer,
            history=None,
            system_prompt=args.system_prompt,
            max_new_tokens=args.max_new_tokens,
            enable_thinking=args.enable_thinking,
            do_sample=args.do_sample,
            temperature=args.temperature,
            top_p=args.top_p,
            top_k=args.top_k,
            repetition_penalty=args.repetition_penalty,
            presence_penalty=args.presence_penalty,
            stream_output=args.stream_output,
        )
        output = postprocess_chat_output(output, enable_thinking=args.enable_thinking)
        if args.stream_output:
            print("", flush=True)
        else:
            print(output, flush=True)
        return

    print("Interactive Qwen3Next hmonnx chat, type '/exit' to quit.", flush=True)
    history = []
    while True:
        try:
            prompt = input("\nUser: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExit.", flush=True)
            break

        if prompt in {"", "/exit", "exit", "quit"}:
            if prompt == "":
                continue
            print("Exit.", flush=True)
            break

        if args.stream_output:
            print("Assistant: ", end="", flush=True)
        output = runtime.chat(
            prompt=prompt,
            tokenizer=tokenizer,
            history=history,
            system_prompt=args.system_prompt,
            max_new_tokens=args.max_new_tokens,
            enable_thinking=args.enable_thinking,
            do_sample=args.do_sample,
            temperature=args.temperature,
            top_p=args.top_p,
            top_k=args.top_k,
            repetition_penalty=args.repetition_penalty,
            presence_penalty=args.presence_penalty,
            stream_output=args.stream_output,
        )
        output = postprocess_chat_output(output, enable_thinking=args.enable_thinking)
        if args.stream_output:
            print("", flush=True)
        else:
            print(f"Assistant: {output}", flush=True)
        history.append({"role": "user", "content": prompt})
        history.append({"role": "assistant", "content": output})


if __name__ == "__main__":
    main()
