# Copyright 2026 HOUMO AI
# SPDX-License-Identifier: Apache-2.0

"""Runtime helpers for Cosmos3-Nano HMONNX execution."""

from .generator_pipeline_runtime import (
    GeneratorVaePipelineOutput,
    GeneratorVaePipelineRuntime,
)
from .generator_scheduler_runtime import (
    GeneratorCfgSchedulerRuntime,
    GeneratorDenoiserHmonnxPath,
    GeneratorHmonnxDenoiserRuntime,
    GeneratorPackedCondition,
    GeneratorSchedulerInputs,
    GeneratorSchedulerOutput,
    GeneratorSchedulerStepTrace,
    GeneratorTorchDenoiserRuntime,
    cfg_combine,
    flatten_latents,
    load_generator_scheduler,
    make_generator_cfg_scheduler_inputs,
    make_timestep_vector,
    unflatten_latents,
)
from .vae_encoder_runtime import (
    VaeEncoderHmonnxPath,
    VaeEncoderHmonnxRuntime,
    make_vae_encoder_sample,
)
from .vae_decoder_runtime import (
    VAE_DECODER_CACHE_LOOP_STAGES,
    VAE_DECODER_SPLIT_STAGES,
    VAE_DECODER_STAGES,
    VaeDecoderCacheLoopStageWrapper,
    VaeDecoderFullHmonnxPaths,
    VaeDecoderFullHmonnxRuntime,
    VaeDecoderHmonnxSplitRuntime,
    VaeDecoderSplitHmonnxPaths,
    VaeDecoderSplitStageWrapper,
    VaeDecoderStageWrapper,
    require_vae_decoder_full_paths,
    require_vae_decoder_split_paths,
    make_vae_decoder_latents,
)
from .reasoner_runtime import (
    IMAGE_TOKEN_ID,
    ReasonerHmonnxPaths,
    ReasonerHmonnxRuntime,
    ReasonerRuntimeInputs,
    ReasonerRuntimeOutput,
    fuse_text_image,
    make_reasoner_inputs,
    require_paths,
)
from .sound_tokenizer_runtime import (
    SOUND_DECODER_SPLIT_STAGES,
    SoundTokenizerDecoderHmonnxPath,
    SoundTokenizerDecoderHmonnxRuntime,
    SoundTokenizerDecoderSplitHmonnxPaths,
    SoundTokenizerDecoderSplitHmonnxRuntime,
    require_sound_decoder_split_paths,
)

__all__ = [
    "GeneratorCfgSchedulerRuntime",
    "GeneratorDenoiserHmonnxPath",
    "GeneratorHmonnxDenoiserRuntime",
    "GeneratorPackedCondition",
    "GeneratorSchedulerInputs",
    "GeneratorSchedulerOutput",
    "GeneratorSchedulerStepTrace",
    "GeneratorTorchDenoiserRuntime",
    "GeneratorVaePipelineRuntime",
    "GeneratorVaePipelineOutput",
    "IMAGE_TOKEN_ID",
    "ReasonerHmonnxPaths",
    "ReasonerHmonnxRuntime",
    "ReasonerRuntimeInputs",
    "ReasonerRuntimeOutput",
    "SoundTokenizerDecoderHmonnxPath",
    "SoundTokenizerDecoderHmonnxRuntime",
    "SoundTokenizerDecoderSplitHmonnxPaths",
    "SoundTokenizerDecoderSplitHmonnxRuntime",
    "SOUND_DECODER_SPLIT_STAGES",
    "make_vae_decoder_latents",
    "VaeEncoderHmonnxRuntime",
    "VaeEncoderHmonnxPath",
    "make_vae_encoder_sample",
    "VaeDecoderStageWrapper",
    "VaeDecoderCacheLoopStageWrapper",
    "VaeDecoderFullHmonnxPaths",
    "VaeDecoderFullHmonnxRuntime",
    "VaeDecoderHmonnxSplitRuntime",
    "VaeDecoderSplitHmonnxPaths",
    "VaeDecoderSplitStageWrapper",
    "VAE_DECODER_STAGES",
    "VAE_DECODER_CACHE_LOOP_STAGES",
    "VAE_DECODER_SPLIT_STAGES",
    "cfg_combine",
    "flatten_latents",
    "fuse_text_image",
    "load_generator_scheduler",
    "make_generator_cfg_scheduler_inputs",
    "make_reasoner_inputs",
    "make_timestep_vector",
    "require_paths",
    "require_sound_decoder_split_paths",
    "require_vae_decoder_full_paths",
    "require_vae_decoder_split_paths",
    "unflatten_latents",
]
