quant: null

export:
  target_device: XH2a
  model:
    type: XHZImageModel
  zimage:
    components: [text_encoder, vae, dit]
    torch_dtype: float16
    batch_size: 1
    context_length: 2048
    input_sequence_length: 256
    quant_type: w8a8h1_sefp
    quant_weight: null
    text_encoder:
      quant_type: w8a8h1_sefp
    vae:
      quant_type: w8a8h1_sefp
    dit:
      quant_type: w8a8h1_sefp
